const $=id=>document.getElementById(id);let currentTask=null,pollTimer=null;
const labels={created:'已创建',queued:'排队中',running:'Agent 执行中',waiting_for_review:'等待审核',completed:'已完成',failed:'执行失败',cancelled:'已取消',review_processing:'处理审核'};
const phases={created:5,waiting_for_worker:12,agent_execution:48,human_review:85,finished:100,failed:100,cancelled_before_start:100};
const split=v=>v.split(/[,，;；]/).map(x=>x.trim()).filter(Boolean);
async function json(url,options){const r=await fetch(url,options);let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.detail||`请求失败 (${r.status})`);return body}
async function health(){try{const h=await json('/health');$('serviceState').textContent=h.execution_mode==='external'?'服务正常 · 独立 Worker':'服务正常 · 开发模式';$('serviceState').classList.remove('bad')}catch{$('serviceState').textContent='服务不可用';$('serviceState').classList.add('bad')}}
$('imageFile').onchange=e=>$('fileName').textContent=e.target.files[0]?.name||'选择图片';
$('taskForm').onsubmit=async e=>{e.preventDefault();$('formError').textContent='';$('submitButton').disabled=true;try{let assetId=null,file=$('imageFile').files[0];if(file){let fd=new FormData();fd.append('file',file);assetId=(await json('/assets',{method:'POST',body:fd})).asset_id}let formats=[...document.querySelectorAll('[name=format]:checked')].map(x=>x.value);if(!formats.length)throw new Error('请至少选择一个输出尺寸');if(assetId)formats=['1:1'];let name=$('brandName').value.trim(),brand=name?{brand_id:name.toLowerCase().replace(/[^a-z0-9_-]/g,'-').replace(/^-+|-+$/g,'')||'brand',name,tone:split($('brandTone').value),primary_colors:split($('colors').value),required_phrases:split($('requiredPhrases').value),forbidden_phrases:split($('forbiddenPhrases').value)}:null;let payload={orchestration_mode:'multi_agent',prompt:$('prompt').value.trim(),candidate_count:+$('candidateCount').value,output_formats:formats,generate_copy:$('generateCopy').checked,review_required:$('reviewRequired').checked};if(assetId)payload.input_asset_id=assetId;if(brand)payload.brand_profile=brand;let task=await json('/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});showTask(task.task_id);await refreshHistory()}catch(err){$('formError').textContent=err.message}finally{$('submitButton').disabled=false}};
function showTask(id){currentTask=id;$('emptyState').classList.add('hidden');$('taskView').classList.remove('hidden');$('taskLabel').textContent=id;$('timeline').innerHTML='';$('gallery').innerHTML='';$('reviewBox').classList.add('hidden');if(pollTimer)clearInterval(pollTimer);poll();pollTimer=setInterval(poll,2000)}
async function poll(){if(!currentTask)return;try{let [task,events]=await Promise.all([json(`/tasks/${currentTask}`),json(`/tasks/${currentTask}/events`)]);renderStatus(task);renderEvents(events.events);if(['completed','waiting_for_review'].includes(task.status))await renderResult();if(['completed','failed','cancelled'].includes(task.status)){clearInterval(pollTimer);pollTimer=null;refreshHistory()}}catch(err){$('phaseText').textContent=err.message}}
function renderStatus(t){$('statusText').textContent=labels[t.status]||t.status;$('phaseText').textContent=t.phase||'';$('progressBar').style.width=(phases[t.phase]||8)+'%';$('cancelButton').style.display=t.status==='queued'?'block':'none';$('reviewBox').classList.toggle('hidden',t.status!=='waiting_for_review')}
function renderEvents(events){$('timeline').innerHTML=events.slice(-6).map(e=>`<li><strong>${labels[e.status]||e.status}</strong>${e.phase||''} · ${new Date(e.created_at).toLocaleTimeString()}</li>`).join('')}
async function renderResult(){try{let result=await json(`/tasks/${currentTask}/result`);$('gallery').innerHTML=result.assets.map(a=>`<article class="asset"><img loading="lazy" src="/tasks/${currentTask}/assets/${a.asset_id}" alt="生成结果"><footer><span>${a.output_format||''}</span><a href="/tasks/${currentTask}/assets/${a.asset_id}" download>下载</a></footer></article>`).join('')}catch{}}
$('cancelButton').onclick=async()=>{if(currentTask&&confirm('确认取消这个排队任务？')){await json(`/tasks/${currentTask}`,{method:'DELETE'});poll()}};
$('approveButton').onclick=()=>review('approve');$('reviseButton').onclick=()=>review('revise');async function review(decision){try{await json(`/tasks/${currentTask}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,feedback:$('reviewFeedback').value,reviewer:'web-user'})});poll()}catch(err){alert(err.message)}}
async function refreshHistory(){try{let data=await json('/tasks?limit=12');$('historyList').innerHTML=data.tasks.length?data.tasks.map(t=>`<article class="history-card" data-id="${t.task_id}"><span class="eyebrow">${t.task_id}</span><p>${escapeHtml(t.prompt)}</p><footer><span class="tag">${labels[t.status]||t.status}</span><span>${new Date(t.updated_at).toLocaleString()}</span></footer></article>`).join(''):'<p>暂无历史任务</p>';document.querySelectorAll('.history-card').forEach(x=>x.onclick=()=>showTask(x.dataset.id))}catch(err){$('historyList').innerHTML=`<p class="error">${err.message}</p>`}}
function escapeHtml(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}$('refreshHistory').onclick=refreshHistory;health();refreshHistory();setInterval(health,30000);
